import os
import json
import random
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

app = Flask(__name__)

# Store generated tongue twisters
generated_tongue_twisters = []

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    global generated_tongue_twisters
    
    # Here we would normally call an LLM API to generate tongue twisters
    # For now, we'll use a placeholder response
    # In a real implementation, you would use Azure OpenAI API
    
    # Placeholder for Hebrew tongue twisters (would be generated by LLM)
    generated_tongue_twisters = [
        "שרה שרה שיר שמח",
        "דן דן דן בדלת דקה",
        "ציפור צייצה צליל צלול",
        "גדי גידל גזר גדול בגינה",
        "רוני רץ רחוק ראה רכבת",
        "פיל פילף פלפל פעם",
        "חיים חלם חלום חדש",
        "טלי טיילה בטיילת",
        "כרמל כתבה כרטיס כחול",
        "מיכל מצאה מטבע מבריק",
        "נועה נתנה נר נאה",
        "סבא סיפר סיפור סודי",
        "עומר עבד עבודה עצומה",
        "צבי צייר ציור צבעוני",
        "קרן קנתה קופסה קטנה",
        "רותי רקדה ריקוד רועש",
        "שלומי שתל שתיל שמנמן",
        "תמר תפרה תיק תכלת",
        "אבי אהב אגס אדום",
        "בני בנה בניין בבוקר"
    ]
    
    return jsonify({'success': True, 'count': len(generated_tongue_twisters)})

@app.route('/random', methods=['GET'])
def get_random():
    global generated_tongue_twisters
    
    if not generated_tongue_twisters:
        return jsonify({'success': False, 'message': 'No tongue twisters generated yet'})
    
    random_tongue_twister = random.choice(generated_tongue_twisters)
    return jsonify({'success': True, 'tongue_twister': random_tongue_twister})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
